Makefile.toml
bindings/dart/example/.gitignore
bindings/dart/example/lib/data_provider/web.dart
bindings/dart/example/pubspec.yaml
bindings/dart/example/web/index.html

`flutter build web` and `flutter run -d chrome` behave differently when bundling the web assets. In `flutter run -d chrome` we can access an asset via `http://localhost:56864/assets/assets/qambert_v0001/qambert.onnx` or `http://localhost:56864/assets/qambert_v0001/qambert.onnx`. With `flutter build web`, on the other hand, we can only access an asset via `http://localhost:56864/assets/assets/qambert_v0001/qambert.onnx`. 
There are several tickets that relate to this problem:
- https://github.com/flutter/flutter/issues/80784
- https://github.com/flutter/flutter/issues/67655
In this PR we change the `_baseAssetUrl` from `/assets` to `/assets/assets` so that it works for both commands.

Fix web assets path

---

.github/workflows/release.yaml

**Ticket:**
[TY-1877]
**Summary**
- exclude dart example 
- exclude building [wasm android library](https://github.com/xaynetwork/xayn_ai_release/tree/staging/android/src/main/jniLibs/arm64-v8a)
- if we were to create a new release now, the wasm lib would still appear as it is in the build cache (the `target` folder)
- however i will change the cache key in [TY-1871] so no need to do it in this pr
[TY-1877]: https://xainag.atlassian.net/browse/TY-1877
[TY-1871]: https://xainag.atlassian.net/browse/TY-1871

TY-1877 exclude dart example in release repo

---

xayn-ai/src/context.rs

We want the similarity from the QA-mBert to weight 70% of the context value, all the other component equally share the rest.

TY 1927 Change weights to  compute contex value

---

xayn-ai/src/embedding/qambert.rs

For some type of result (video, images, ...) we don't have snippets but only the title.
When running QA-mBert we use the title if the snippet is empty.

TY 1928 With QA-mBert use title if snippet is empty.

---

.github/workflows/ci.yml
.github/workflows/release.yaml

**Ticket**
[TY-1871]
**Summary**
- use `github.job` instead of a hardcoded string to make it less error-prone when copying an exisiting job to use it as a template for a new job 
[TY-1871]: https://xainag.atlassian.net/browse/TY-1871

TY-1871 use github.job in cache key

---

Cargo.lock
xayn-ai/Cargo.toml
xayn-ai/src/lib.rs
xayn-ai/src/reranker/mod.rs

Run tests on the reranker with both `Search` and `News` mode.

Run tests for all rerank mode

---

.ci/install-wasm-pack/action.yml

https://github.com/rustwasm/wasm-pack/releases/tag/v0.10.0
v0.10.0 creates the same bindings as with v0.9.0 in the release ci

Upgrade wasm-pack to 0.10.0

---

.github/workflows/audit.yml

The job failed because the cargo audit output contained backticks that must be escaped, otherwise they will be interpreted as javascript backticks

Fix cargo audit

---

Cross.toml

**Summary**
Pass through `CARGO_INCREMENTAL` to cross. Unfortunately it does not fix the error that appeared in #142

pass cargo env to cross

---

xayn-ai-ffi-c/src/reranker/ai.rs
xayn-ai-ffi-wasm/src/ai.rs
xayn-ai/src/coi/merge.rs
xayn-ai/src/coi/mod.rs
xayn-ai/src/data/mod.rs
xayn-ai/src/embedding/utils.rs
xayn-ai/src/reranker/database.rs
xayn-ai/src/reranker/mod.rs
xayn-ai/src/reranker/sync.rs
xayn-ai/src/utils.rs

**Summary**
adds the ability to sync the internal state of the reranker (currently consists of just the CoIs) between devices.
new `reranker::sync` module:
* reranker data's user interests (i.e. CoIs) now wrapped in a `SyncData`, a new serializable struct.
* `SyncData` exposes a `synchronize` method to sync with another.
* the core of the synchronization algorithm involves _merging_ local CoIs with remote CoIs (see below).
new `coi::merge` module:
* a function `reduce_cois` that reduces a collection of CoIs by successively merging the closest _coiple_.
* a coiple (represented by the struct `Coiple`) is a pair of CoIs considered "close" to each other.
* ability to `merge` added to CoIs (specifically, the `CoiPoint` trait).
**Follow up**
* when synchronizing local with remote CoIs, …

TY-1895/6 synchronizable reranker data

---

xayn-ai/src/ltr/list_net/mod.rs
xayn-ai/src/ltr/list_net/ndlayers/dense.rs
xayn-ai/src/ltr/list_net/ndutils/mod.rs
xayn-ai/src/utils.rs

Implemented initialization of ListNet based on random weights.
Weights are initialized using the He-Normal initialization and
biases are initialized  to 0.
This is based on PR #142, but can be separately reviewed (select to only show changes of the last commit).

Ty 1921 list net training random weights init

---

xayn-ai/Cargo.toml
xayn-ai/src/coi/merge.rs
xayn-ai/src/coi/system.rs
xayn-ai/src/coi/utils.rs
xayn-ai/src/context.rs
xayn-ai/src/data/document_data.rs
xayn-ai/src/data/mod.rs
xayn-ai/src/ltr/mod.rs
xayn-ai/src/mab.rs
xayn-ai/src/reranker/sync.rs
xayn-ai/src/tests/utils.rs
xayn-ai/src/utils.rs

**Summary**
a follow up to #143 for synchronization to support global consistency of CoI ids. 
- refactors `CoiId(usize)` to `CoiId(Uuid)`, and various functions (e.g. methods of `CoiPoint`) to hide the underlying type.
- a new id is now assigned to a CoI whenever it is updated locally.
- duplicate CoIs (indicated by clashing ids) are removed during synchronization.

TY-1952 sync coi ids

---

bindings/dart/example/lib/data_provider/mobile.dart
bindings/dart/example/lib/data_provider/web.dart
bindings/dart/lib/src/common/reranker/data_provider.dart
bindings/dart/lib/src/mobile/reranker/data_provider.dart
bindings/dart/lib/src/web/reranker/data_provider.dart
data/asset_templates/assets.dart.tmpl

**Ticket**
- [TY-1978]
**Summary**
- renamed `suffix` to `urlSuffix`
- moved the checksum method into a new `Checksum` class
- added a `fragments` field to the `Asset` class
- each `Fragment` consists of a `checksum` and a `urlSuffix`
- updated the example
[TY-1978]: https://xainag.atlassian.net/browse/TY-1978

TY-1978 update metadata

---

Cargo.lock
rubert/Cargo.toml
rubert/benches/parallel.rs

**References**
- [TY-1991]
- [rust book on parallelism](https://doc.rust-lang.org/book/ch16-00-concurrency.html)
- [rustonomicon on parallelism](https://doc.rust-lang.org/nomicon/concurrency.html)
**Use case constraints**
- MBert pipeline and sequence only taken by shared reference to produce an embedding
- MBert pipelines can run independently and take the same batch of sequences as input
- each MBert pipeline can run the sequences/samples of the batch independently
**Memory sharing vs message passing**
- parallelization of batch looping is straight forward (e.g. with `rayon`), parallelization of pipelines is also kind of easy due to shared references; passing messages would probably require a clone of the pipeline per channel (maybe `Arc`ing works as well?)
- little change needed, ios & …

TY-1991 parallelization benchmarks

---

CHANGELOG.md
bindings/dart/lib/src/common/reranker/ai.dart
bindings/dart/lib/src/common/result/error.dart
bindings/dart/lib/src/mobile/reranker/ai.dart
bindings/dart/lib/src/web/reranker/ai.dart
bindings/dart/test/mobile/reranker/ai_test.dart
xayn-ai-ffi-c/src/reranker/ai.rs
xayn-ai-ffi-wasm/src/ai.rs
xayn-ai-ffi/src/error.rs
xayn-ai/src/reranker/mod.rs
xayn-ai/src/reranker/public.rs
xayn-ai/src/reranker/sync.rs

**Summary**
previous related: #143, #152.
- exposes the functions `syncdata_bytes`, `synchronize` to ffi layers and dart binding.
- corresponding tests.
- handles panic when empty passed to `synchronize` (see `sync.rs`).
- updates changelog.

TY-1897 expose sync methods to ffi

---

.github/workflows/ci.yml

The CI is sometimes falling because the tests of `test-android-libs (aarch64-linux-android)`[ take longer than 20 min](https://github.com/xaynetwork/xayn_ai/runs/3289654229).
This RP increases the timeout to 30 min.

increase timeout to 30 min

---

Cargo.lock
dev-tool/Cargo.toml
dev-tool/src/list_net.rs
dev-tool/src/list_net/convert.rs
dev-tool/src/list_net/data_source.rs
dev-tool/src/main.rs

This adds the `dev-tool list-net convert` sub-command which can be used to convert a folder with soundgarden user data frame csv files to a `<name>.samples` file (which is a bincode serialized version of `InMemorySamples`).
For the 500_000 samples with are ~5.4GiB unpacked on disk this will produce a 875MiB file. Which if compiled in release mode will load in ~1s (or ~50s if not in release mode).
The `<name>.samples` files are used for training using soundgarden data, both with the classical training which is added in part 3 and the XaynNet emulation training which will be added in a followup PR.
PS:
Also don't forget that each split out PR will contain all changes of the previous PR until that is merged and this PR is rebased so this PR doesn't have ~2200 changes but ~1800.

TY-1931 ListNet training with soundgarden: Split PR, part 2. Add samples preparation CLI.

---

Cargo.lock
dev-tool/Cargo.toml
dev-tool/src/list_net.rs
dev-tool/src/list_net/cli_callbacks.rs
dev-tool/src/list_net/data_source.rs
dev-tool/src/list_net/train.rs
xayn-ai/src/ltr/list_net/mod.rs
xayn-ai/src/ltr/list_net/tests/training.rs

Allows training of a ListNet using soundgarden data converted to a `.samples` file.
This doesn't yet include the emulation of `XaynNet`.
Some features like choosing a weight initializer, parallelized training or better support for huge batch sizes 
are done in a follow up PR.
Side note: 
A follow up PR parallelizes the training speeding it up by quite a bit, especially if run in release mode.

TY-1931 ListNet training with soundgarden: Split PR, part 3. Add train CLI.

---

Cargo.lock
xayn-ai-ffi/Cargo.toml
xayn-ai/Cargo.toml
xayn-ai/src/embedding/qambert.rs
xayn-ai/src/embedding/smbert.rs

**Ticket:**
- [TY-2002]
**Summary**
- adds a `parallel` feature flag that parallelizes the loops over the documents in the S/QAMbertSystem's implementations with rayon's par_iter()
I will do the integration for the mobile version in [TY-2042]
[TY-2002]: https://xainag.atlassian.net/browse/TY-2002
[TY-2042]: https://xainag.atlassian.net/browse/TY-2042

TY-2002 Add rayon for running bert models in parallel

---

.github/workflows/ci.yml
.github/workflows/release.yaml
Makefile.toml

Specifically both `build-ios` and `build-android` tried to potentially build _all_ workspaces. Including `xayn-ai-ffi-wasm` and
`dev-tool`. But `dev-tool` has neither lib nor main entry point on mobile and `cargo ndk` still tries to forceful build a
binary. This then fail making `cargo make build-android` fail.
The `cargo lipo` command used on `cargo make build-ios` has conceptually the same problem but only considers workspaces which create `staticlib`s, which means the bug should not have triggered.

Fix bug in cargo make build-mobile.

---

xayn-ai/src/coi/merge.rs
xayn-ai/src/reranker/database.rs
xayn-ai/src/reranker/sync.rs
xayn-ai/src/tests/mod.rs
xayn-ai/src/tests/utils.rs
xayn-ai/src/utils.rs

**Summary**
previous related: #143, #152, #154.
adds unit tests for the `sync` and `merge` modules.
* adds a migration test to `database` module, factors out `serialize_with_version` into test utils.
* tests for `SyncData` methods, specifically `deserialize` and `synchronize`.
* particular cases for "identity" and "commutativity" laws.
* tests for `CoiPair` & `Coiple` methods, and `reduce_cois` function.

TY-1899 tests for sync & merge

---

dev-tool/src/list_net.rs
dev-tool/src/list_net/cli_callbacks.rs
dev-tool/src/list_net/data_source.rs
dev-tool/src/list_net/evaluate.rs
dev-tool/src/list_net/train.rs
xayn-ai/src/ltr/list_net/mod.rs
xayn-ai/src/ltr/list_net/tests/training.rs

Based on PR #163.
This does some refactoring as well as:
- Adds a `dev-tool list-net evaluate` command allowing the comparison of existing ListNets.
- Adds support for parallel evaluation of samples.
- Adds a single batch training mode  (batch_size=0 => batch_size=nr_of_training_samples).

Ty 1932 part 2 further improve dev tool training

---

dev-tool/src/list_net/convert.rs
dev-tool/src/list_net/data_source.rs
dev-tool/src/list_net/evaluate.rs
dev-tool/src/list_net/train.rs
xayn-ai/src/ltr/list_net/mod.rs
xayn-ai/src/ltr/list_net/tests/training.rs

The data source currently has one sample per user but we treat it as many samples for one user.
For XaynNet training emulation we need to pretend each user has multiple samples (in PR part-6 each
user has multiple samples but we still need to merge some them as users in the training database have 
too little history compared to real users).

Ty 1932 part 4 support chunking data source

---

.github/workflows/ci.yml
Cargo.lock
bindings/dart/lib/src/common/result/error.dart
bindings/dart/lib/src/mobile/reranker/ai.dart
xayn-ai-ffi-c/Cargo.toml
xayn-ai-ffi-c/src/reranker/ai.rs
xayn-ai-ffi-c/src/utils.rs
xayn-ai-ffi/Cargo.toml
xayn-ai-ffi/src/error.rs

**Ticket:**
- [TY-2024]
**Summary:**
- added the initialization of thread pool in the mobile target
- Android tests compiled with the default feature `parallel` are failing when running them via `cross`. However, they are not failing on the emulator/real device. We agreed to run the Android test without the feature `parallel` and tackle this issue in a later pr.
Checks:
[TY-2024]: https://xainag.atlassian.net/browse/TY-2024

TY-2042 add init thread pool function

---

Cargo.lock
Cargo.toml
Makefile.toml
README.md
bindings/dart/example/flutter_run_web.sh
bindings/dart/example/server.py
bindings/dart/example/web/index.html
bindings/dart/lib/src/common/data/history.dart
bindings/dart/lib/src/common/reranker/ai.dart
bindings/dart/lib/src/common/reranker/debug.dart
bindings/dart/lib/src/mobile/reranker/ai.dart
bindings/dart/lib/src/mobile/result/outcomes.dart
bindings/dart/lib/src/web/ffi/library.dart
bindings/dart/lib/src/web/reranker/ai.dart
bindings/dart/pubspec.yaml
bindings/dart/test/mobile/reranker/ai_test.dart
bindings/dart/test/mobile/result/outcomes_test.dart
xayn-ai-ffi-wasm/Cargo.toml
xayn-ai-ffi-wasm/src/lib.rs

Adds support for building parallelized WASM:
it doesn't manual test the dart bindings (which is what matters) and it's a bunch of additional
maintenance overhead.
- This does not update the CI, the CI will run like before, but this also mean it won't run or build the parallelized
WASM.
- This doesn't run wasm bindgen tests with parallelized wasm, it's not clear how to do so tbh.
- This doesn't include a bundler, at least for now we don't need it.
This should be merged after similar changes for the C-FFI had been made.

TY 2034 Add parallel WASM initializer.

---

.github/workflows/release.yaml

This needs to be backported to let the release CI work correctly. At the moment it fails because the tags are already on the release repo and they cannot be overridden.

Don't push tags to release repository 

---

.github/workflows/release.yaml

~I will still create the relevant secrets, but as far as the changes go, this covers it.~ New secrets are there! 🎉 
The diff looks odd because it matches part of what was in the middle of the KeyCDN part, but actually all KeyCDN content is gone and now we just have a split logic for uploading assets to either Staging or Production S3 buckets.
Signed-off-by: Ricardo Saffi Marques <ricardo.marques@xayn.com>

DEVOPS-485 Adjust CI for publishing of AI Assets to Staging or Production buckets

---

bindings/dart/lib/src/common/reranker/ai.dart

**References**
- [TY-2068]
**Summary**
- introduce a `maxNumberOfThreads` constant to limit the maximum number of threads to be used, it's currently set to 16 which is somewhat arbitrary
[TY-2068]: https://xainag.atlassian.net/browse/TY-2068

TY-2068 limit max threads

---

.ci/build-asset-artifacts/action.yml
.github/workflows/release.yaml
Makefile.toml
assets_manifest.json
bindings/dart/example/lib/data_provider/data_provider.dart
bindings/dart/example/lib/data_provider/mobile.dart
bindings/dart/example/lib/data_provider/web.dart
bindings/dart/example/lib/logic.dart
bindings/dart/example/lib/main.dart
bindings/dart/lib/package.dart
bindings/dart/lib/src/common/reranker/data_provider.dart
bindings/dart/lib/src/mobile/reranker/data_provider.dart
bindings/dart/lib/src/web/reranker/data_provider.dart
bindings/dart/test/mobile/utils.dart
generate_assets_metadata.sh
xayn-ai-ffi-wasm/Cargo.toml

**References**
- [TY-2069]
- [TY-2066]
**Summary**
- add an optional set of  `Feature`s to select the respective assets for sequential/parallel mobile/web in dart
- update the corresponding `getAssets()`, `SetupData()` functions and pick a default in the example app
- expand the asset generation script to generate sequential/parallel web assets depending on the input
- update the makefile to generate the sequential/parallel web assets depending on `DISABLE_WASM_THREADS`
- update the release ci to build the sequential/parallel web artifacts
**Todo**
- ~rebase once #207 is merged~
**Open questions**
- testing for mobile and sequential web was successful, but when trying to test the parallel web it loads indefinitely (i tried firefox) where i'm not sure if this is related to these changes or …

TY-2069 Update assets script

---

bindings/dart/pubspec.yaml

* App cannot use flutter 2.5 yet.
* Adjust dart version to allow `pre` versions.
I think we can keep 2.5 in the CI. We are not really using any flutter feature here.

Revert dart and flutter version

---

bindings/dart/lib/src/mobile/reranker/data_provider.dart
bindings/dart/lib/src/web/reranker/data_provider.dart
generate_assets_metadata.sh

Rename the asset named `wasmSequentialX` to `wasmX` to keep compatibility with previous version.

Rename wasmSequentialX to wasmX

---

.github/workflows/release.yaml

Ticket: 
- [TY-2106]
Summary:
- disables the mime detection via `python-magic`
- s3cmd only uses the file extension to guess the right mime type ([Understand Content Type, Mime type guessing and Magic](https://github.com/s3tools/s3cmd/wiki/Understand-Content-Type,-Mime-type-guessing-and-Magic))
- for wasm files the mime type is now ->  `application/wasm`
- and for js files ->  `application/javascript`
[TY-2106]: https://xainag.atlassian.net/browse/TY-2106

TY-2106 fix mime type detection

---

.github/workflows/ci.yml
.github/workflows/release.yaml

Ticket: 
- [TY-2105]
Summary:
- updated the ci runners to `macos-11`
- set `xcode-13` as default version
~Should we create a ticket to remove the `DEVELOPER_DIR` env once xcode 13 becomes the default?~(done)
[TY-2105]: https://xainag.atlassian.net/browse/TY-2105

TY-2105 upgrade runners to macos-11

---

.github/workflows/release.yaml

We don't want to accidentally override existing files but only upload those that are new.

add --skip-existing flag

---

xayn-ai/src/coi/system.rs
xayn-ai/src/coi/utils.rs
xayn-ai/src/data/document_data.rs
xayn-ai/src/embedding/qambert.rs
xayn-ai/src/ltr/features/mod.rs
xayn-ai/src/ltr/mod.rs
xayn-ai/src/reranker/mod.rs
xayn-ai/src/reranker/systems.rs
xayn-ai/src/tests/systems.rs
xayn-ai/src/tests/utils.rs

The coi system depends on the smbert, keeping them in sequence helps in have cleaner code when we have to skip coi if smbert failed.
This mainly change DocumentData to have the order smbert, coi, qambert.
Who was taking in input:
`DocumentDataWithSMBert` now needs `DocumentDataWithCoi`,
`DocumentDataWithQAMBert` now needs `DocumentDataWithSMBert`,
`DocumentDataWithCoi` now needs `DocumentDataWithQAMBert`.

TY-2079 [0] Keep smbert and coi together

---

xayn-ai/src/coi/system.rs
xayn-ai/src/data/document_data.rs
xayn-ai/src/embedding/qambert.rs
xayn-ai/src/embedding/smbert.rs
xayn-ai/src/ltr/mod.rs
xayn-ai/src/reranker/mod.rs
xayn-ai/src/reranker/systems.rs
xayn-ai/src/tests/systems.rs
xayn-ai/src/tests/utils.rs

Since now we want to have fallback strategies we cannot take ownership of the documents in the systems.
Systems are now taking a slice.
I didn't do it for the context system because it is the last one that gets the data and there is not fallback for it.
This is based on #265, only the last commit belongs to this PR.

TY 2079 [1] System takes documents as immutable 
